### ISSUE TITLE
Language conversion isn't implemented?

### ISSUE THREAD

**Issue by b-fuze** [hardpixel/tm2gsv#1]
Hi, I wanted to use this to convert some tmLanguage syntax files to GTKSourceView but it didn't work as per the instructions I followed in your readme, it simply exited with no feedback...

I read the sources of tm2gsv and the Tm2Gsv::Language class looks barren in comparison to Tm2Gsv::Theme, will you be implementing this feature soon?

**Comment by jonian** [comment]
Hi @b-fuze. Apologies for the very late response. No, language conversion is not implemented. It is mentioned in readme as WIP.
